modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="faatgrmod"
version="${file.jarVersion}"
displayName="Fossils and Archaeology The Great Reset Mod"
logoFile="biofossil"
credits="the great reset"
authors="plants"
description='''
Mod by Bazinga
'''
[[dependencies.faatgrmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.faatgrmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
